[program:Chromium]
command=bash -c 'chromium --disable-sync --disable-popup-blocking --disable-dev-shm-usage --disable-gpu --start-maximized --force-device-scale-factor=1 --remote-debugging-port=9223 --remote-debugging-address=127.0.0.1'
priority=5
autorestart=true
stderr_logfile=/var/log/chromium.err.log
